name = "PointerArithmetic"
uuid = "c94a8726-515c-4ee5-9c02-6a0d0dc456e9"
authors = ["nickolasrm <nickolasrochamachado@gmail.com>"]
version = "0.2.1"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Reexport = "0, 1"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
